name: Release candidate
on:
  push:
    branches:
      - "change/**"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint, unit test
        run: make test
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run Container
        run: ENV=github-actions make run-container
      - name: Service Test
        run: ENV=github-actions make service-test
      - name: Publish to Dockerhub
        run: ENV=github-actions make publish-image
