name: Release candidate
on:
  push:
    branches:
      - "change/**"

jobs:
  check_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint, unit test
        run: make test
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Run Container
        run: ENV=github-actions make run-container
      - name: Service Test
        run: ENV=github-actions make service-test
      - name: Publish to Dockerhub
        run: ENV=github-actions make publish-image
